# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatAdminStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IniciaChat = channel.unary_stream(
        '/ChatAdmin/IniciaChat',
        request_serializer=chat__pb2.Usuarios.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.Subscribirse = channel.unary_unary(
        '/ChatAdmin/Subscribirse',
        request_serializer=chat__pb2.CrearUsuarioRequest.SerializeToString,
        response_deserializer=chat__pb2.Respuesta.FromString,
        )
    self.EliminaMensaje = channel.unary_unary(
        '/ChatAdmin/EliminaMensaje',
        request_serializer=chat__pb2.Mensaje.SerializeToString,
        response_deserializer=chat__pb2.Respuesta.FromString,
        )


class ChatAdminServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IniciaChat(self, request, context):
    """Inicia un chat entre dos clientes y permite mandar menasjes
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribirse(self, request, context):
    """Se agrega al servidor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EliminaMensaje(self, request, context):
    """Elimina mensaje
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatAdminServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IniciaChat': grpc.unary_stream_rpc_method_handler(
          servicer.IniciaChat,
          request_deserializer=chat__pb2.Usuarios.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'Subscribirse': grpc.unary_unary_rpc_method_handler(
          servicer.Subscribirse,
          request_deserializer=chat__pb2.CrearUsuarioRequest.FromString,
          response_serializer=chat__pb2.Respuesta.SerializeToString,
      ),
      'EliminaMensaje': grpc.unary_unary_rpc_method_handler(
          servicer.EliminaMensaje,
          request_deserializer=chat__pb2.Mensaje.FromString,
          response_serializer=chat__pb2.Respuesta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChatAdmin', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
