# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"%\n\x08Usuarios\x12\x19\n\x07usuario\x18\x01 \x03(\x0b\x32\x08.Usuario\"7\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\x08\"/\n\x12\x43rearUsuarioResult\x12\x19\n\x07usuario\x18\x01 \x01(\x0b\x32\x08.Usuario\"0\n\x13\x43rearUsuarioRequest\x12\x19\n\x07usuario\x18\x01 \x01(\x0b\x32\x08.Usuario\"\x1e\n\tRespuesta\x12\x11\n\trespuesta\x18\x01 \x01(\t\"&\n\x07Mensaje\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x8a\x01\n\tChatAdmin\x12#\n\nIniciaChat\x12\t.Usuarios\x1a\x08.Mensaje0\x01\x12\x30\n\x0cSubscribirse\x12\x14.CrearUsuarioRequest\x1a\n.Respuesta\x12&\n\x0e\x45liminaMensaje\x12\x08.Mensaje\x1a\n.Respuestab\x06proto3')
)




_USUARIOS = _descriptor.Descriptor(
  name='Usuarios',
  full_name='Usuarios',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='Usuarios.usuario', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=51,
)


_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Usuario.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='Usuario.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estado', full_name='Usuario.estado', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=108,
)


_CREARUSUARIORESULT = _descriptor.Descriptor(
  name='CrearUsuarioResult',
  full_name='CrearUsuarioResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='CrearUsuarioResult.usuario', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=157,
)


_CREARUSUARIOREQUEST = _descriptor.Descriptor(
  name='CrearUsuarioRequest',
  full_name='CrearUsuarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='CrearUsuarioRequest.usuario', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=207,
)


_RESPUESTA = _descriptor.Descriptor(
  name='Respuesta',
  full_name='Respuesta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='Respuesta.respuesta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=239,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Mensaje.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Mensaje.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=279,
)

_USUARIOS.fields_by_name['usuario'].message_type = _USUARIO
_CREARUSUARIORESULT.fields_by_name['usuario'].message_type = _USUARIO
_CREARUSUARIOREQUEST.fields_by_name['usuario'].message_type = _USUARIO
DESCRIPTOR.message_types_by_name['Usuarios'] = _USUARIOS
DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['CrearUsuarioResult'] = _CREARUSUARIORESULT
DESCRIPTOR.message_types_by_name['CrearUsuarioRequest'] = _CREARUSUARIOREQUEST
DESCRIPTOR.message_types_by_name['Respuesta'] = _RESPUESTA
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Usuarios = _reflection.GeneratedProtocolMessageType('Usuarios', (_message.Message,), {
  'DESCRIPTOR' : _USUARIOS,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Usuarios)
  })
_sym_db.RegisterMessage(Usuarios)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), {
  'DESCRIPTOR' : _USUARIO,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Usuario)
  })
_sym_db.RegisterMessage(Usuario)

CrearUsuarioResult = _reflection.GeneratedProtocolMessageType('CrearUsuarioResult', (_message.Message,), {
  'DESCRIPTOR' : _CREARUSUARIORESULT,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:CrearUsuarioResult)
  })
_sym_db.RegisterMessage(CrearUsuarioResult)

CrearUsuarioRequest = _reflection.GeneratedProtocolMessageType('CrearUsuarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREARUSUARIOREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:CrearUsuarioRequest)
  })
_sym_db.RegisterMessage(CrearUsuarioRequest)

Respuesta = _reflection.GeneratedProtocolMessageType('Respuesta', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTA,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Respuesta)
  })
_sym_db.RegisterMessage(Respuesta)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)



_CHATADMIN = _descriptor.ServiceDescriptor(
  name='ChatAdmin',
  full_name='ChatAdmin',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=282,
  serialized_end=420,
  methods=[
  _descriptor.MethodDescriptor(
    name='IniciaChat',
    full_name='ChatAdmin.IniciaChat',
    index=0,
    containing_service=None,
    input_type=_USUARIOS,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribirse',
    full_name='ChatAdmin.Subscribirse',
    index=1,
    containing_service=None,
    input_type=_CREARUSUARIOREQUEST,
    output_type=_RESPUESTA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EliminaMensaje',
    full_name='ChatAdmin.EliminaMensaje',
    index=2,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_RESPUESTA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATADMIN)

DESCRIPTOR.services_by_name['ChatAdmin'] = _CHATADMIN

# @@protoc_insertion_point(module_scope)
